/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LineRouteImport } from './routes/line'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as StageTemplatesRouteImport } from './routes/stage-templates'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LineRoute = LineRouteImport.update({
  id: '/line',
  path: '/line',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const StageTemplatesRoute = StageTemplatesRouteImport.update({
  id: '/stage-templates',
  path: '/stage-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/stage-templates': typeof StageTemplatesRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/stage-templates': typeof StageTemplatesRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/quotes': typeof QuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/line': typeof LineRoute
  '/login': typeof LoginRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/stage-templates': typeof StageTemplatesRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/expenses'
    | '/line'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/stage-templates'
    | '/admin/modules'
    | '/admin/tenants'
    | '/admin/users'
    | '/projects/$id'
    | '/quotes/$id'
    | '/projects/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/expenses'
    | '/line'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/stage-templates'
    | '/admin/modules'
    | '/admin/tenants'
    | '/admin/users'
    | '/projects/$id'
    | '/quotes/$id'
    | '/projects'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/expenses'
    | '/line'
    | '/login'
    | '/payables'
    | '/receivables'
    | '/stage-templates'
    | '/admin/modules'
    | '/admin/tenants'
    | '/admin/users'
    | '/projects/$id'
    | '/quotes/$id'
    | '/projects/'
    | '/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  ExpensesRoute: typeof ExpensesRoute
  LineRoute: typeof LineRoute
  LoginRoute: typeof LoginRoute
  PayablesRoute: typeof PayablesRoute
  ReceivablesRoute: typeof ReceivablesRoute
  StageTemplatesRoute: typeof StageTemplatesRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  QuotesIdRoute: typeof QuotesIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line': {
      id: '/line'
      path: '/line'
      fullPath: '/line'
      preLoaderRoute: typeof LineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-templates': {
      id: '/stage-templates'
      path: '/stage-templates'
      fullPath: '/stage-templates'
      preLoaderRoute: typeof StageTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  ExpensesRoute: ExpensesRoute,
  LineRoute: LineRoute,
  LoginRoute: LoginRoute,
  PayablesRoute: PayablesRoute,
  ReceivablesRoute: ReceivablesRoute,
  StageTemplatesRoute: StageTemplatesRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  QuotesIdRoute: QuotesIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
